### ISSUE TITLE
Tokenizer.setCompositeTokensPatterns() does not handle regular expressions!

### ISSUE THREAD

**Issue by Tshimanga** [JohnSnowLabs/spark-nlp#484] opened 2019-04-12 19:49 UTC
## Description
If you use a regular expression to protect composite tokens from breakage. There are a couple issue (so far) that arise that make the method unusable:

##  Current Behavior
1) The token.result value is the pattern used to match the substring(s) of interest.
2) The token.end value is the "beginning of matched substring" plus "length of pattern used" minus 1
## Expected Behavior
1) token.result should be the matched substring
2) token.end should be the end of the matched substring

## Steps to Reproduce
Re-run the unit test
````
  val targetText = "Hello, I won't be from New York in the U.S.A. (and you know it héroe). Give me my horse! or $100" +
    " bucks 'He said', I'll defeat markus-crassus. You understand. Goodbye George E. Bush. www.google.com."
  val expected = Array(
    "Hello", ",", "I", "wo", "n't", "be", "from", "New York", "in", "the", "U.S.A.", "(", "and", "you", "know", "it",
    "héroe", ")", ".", "Give", "me", "my", "horse", "!", "or", "$100", "bucks", "'", "He", "said", "'", ",", "I", "'ll",
    "defeat", "markus-crassus", ".", "You", "understand", ".", "Goodbye", "George", "E.", "Bush", ".", "www.google.com", "."
  )

  "a Tokenizer" should "correctly tokenize target text on its defaults parameters with composite" in {
    val data = DataBuilder.basicDataBuild(targetText)
    val document = new DocumentAssembler().setInputCol("text").setOutputCol("document")
    val tokenizer = new Tokenizer().setInputCols("document").setOutputCol("token").setCompositeTokensPatterns(Array("New York"))
    val finisher = new Finisher().setInputCols("token").setOutputAsArray(true).setCleanAnnotations(false).setOutputCols("output")
    val pipeline = new Pipeline().setStages(Array(document, tokenizer, finisher))
    val pip = pipeline.fit(data).transform(data)
    val result = pip
      .select("output").as[Array[String]]
      .collect.flatten
    assert(
      result.sameElements(expected),
      s"because result tokens differ: " +
        s"\nresult was \n${result.mkString("|")} \nexpected is: \n${expected.mkString("|")}"
    )
    pip
      .select("token").as[Array[Annotation]]
      .collect.foreach(annotations => {
      annotations.foreach(annotation => {
        assert(targetText.slice(annotation.begin, annotation.end + 1) == annotation.result)
      })
    })
  }
````
with regex `Ne.*ork` to match "New York" and watch the test break.

## Context
Can not use the method to protect redacted tokens in medical text. Causing a delay in development.

## Your Environment
Initially observed in a jupyter notebook, preproduced in spark-nlp unit test locally.

**Comment by atomobianco** [comment] 2019-07-18 13:21
I have the same problem, regex wronlgy interpreted, maybe because using a surrounding group?

PS: it seems that the argument is now called `exceptions`, and one can set custom exceptions with `setExceptions`.

```
import com.johnsnowlabs.nlp.{DocumentAssembler, Finisher}
import com.johnsnowlabs.nlp.annotator.{SentenceDetector, Tokenizer}

val documentAssembler = new DocumentAssembler().setInputCol("text").setOutputCol("document")

val sentenceDetector = new SentenceDetector().setInputCols("document").setOutputCol("sentence")

val tokenizer = new Tokenizer().setInputCols("sentence").setOutputCol("token")
    .setExceptions(Array("""(\d[\d ]+\d)""")) // https://regex101.com/r/4TZShk/2

val finisher = new Finisher().setInputCols("token").setOutputCols("final")

val pipeline = new Pipeline().
    setStages(Array(
        documentAssembler,
        sentenceDetector,
        tokenizer,
        finisher
    ))

val testDf = Seq("the sum of 45 822 euros to be payed").toDF("text")

pipeline
    .fit(testDf)
    .transform(testDf)
    .show(false)
```

Result:
```
+-----------------------------------+-----------------------------------------------+
|text                               |final                                          |
+-----------------------------------+-----------------------------------------------+
|the sum of 45 822 euros to be payed|[the, sum, of, 45 822 eu, euros, to, be, payed]|
+-----------------------------------+-----------------------------------------------+

documentAssembler = document_f1b356d83520
sentenceDetector = SENTENCE_2f9959db71b7
tokenizer = REGEX_TOKENIZER_8e01857afe2e
finisher = finisher_02bd895189cd
pipeline = pipeline_e2ec6e1157a9
testDf = [text: string]
```

**Comment by maziyarpanahi** [comment] 2019-07-18 14:20
HI @atomobianco 

Thanks for providing the code to reproduce this issue and especially the link to regex101. In `2.1.0` the exceptions and compositeTokens were merged together which is called `setExceptions` as you correctly mentioned.
Without setting any rules and exceptions the sentence will be:
```
the, sum, of, 45, 822, euros, to, be, payed
```
So the number breaks into `45, 822`. But with your regular expression it turned into:
```
the, sum, of, 45 822 eu, euros, to, be, payed
```
It just has that `eu` part which it shouldn't be there by testing the regex in https://regex101.com/r/4TZShk/2

So is not so much about not accepting a regular expression as it didn't perform correctly, am I right?

**Comment by atomobianco** [comment] 2019-07-18 15:09
> So is not so much about not accepting a regular expression as it didn't perform correctly, am I right?
Yes, it's about not performing as expected.
I tried different regex combinations, but none working as expected.
I would also like to use regex with full flavours, like look-behind/ahead, non-capturing groups, etc. if possible. 

What I am trying to do is keep monetary amounts (but could be numbers in general) as single tokens, to later clean them with the `Normalizer`, so that `45 822,23` can become `45822.23` (I left the decimal part out of the issue for simplicity).

**Comment by saifjsl** [comment] 2019-08-15 12:52
Thanks @atomobianco I think this is quite straight forward to support in the new `TokenizerModel`:

```
  private def casedMatchExists (candidateMatched: String): Boolean =
    if ($(caseSensitiveExceptions))
      $(exceptions).contains(candidateMatched)
    else
      $(exceptions).map(_.toLowerCase).contains(candidateMatched.toLowerCase)
```

We can add this functionality for upcoming release

**Comment by saifjsl** [comment] 2019-08-16 01:23
Merged in release candidate https://github.com/JohnSnowLabs/spark-nlp/pull/593

**Closed by saifjsl** 2019-08-16 01:23 UTC
