### ISSUE TITLE
TypeError: 'JavaPackage' object is not callable

### ISSUE THREAD

**Issue by bigheadming** [JohnSnowLabs/spark-nlp#232] opened 2018-06-22 16:59 UTC
Get "TypeError: 'JavaPackage' object is not callable " error whenever trying to call any annotators.  
## Description

Platform: Ubuntu 16.04LTS on Windows 10's Linux System (wls)
Python: Python 3.6.4 |Anaconda custom (64-bit)| (default, Jan 16 2018, 18:10:19)
Pyspark:  Use pip to install (ie python without explcit spark installation)
spark-nlp: pip install --index-url https://test.pypi.org/simple/ spark-nlp==1.5.4

Tried running the followings, but all returned with the same "TypeError: 'JavaPackage' object is not callable " error. There seems to have a similar bug "Python annotators should be loadable on its own #91" that was closed sometime ago, but it still happened to me. 

from pyspark.sql import SparkSession
spark = SparkSession \\
  .builder \\
  .config("spark.driver.extraClassPath", "lib/sparknlp.jar") \\
  .getOrCreate()

from sparknlp.annotator import *
from sparknlp.common import *
from sparknlp.base import *

documentAssembler = DocumentAssembler()\
  .setInputCol("text")\
  .setOutputCol("document")

lemmatizer = Lemmatizer() \
  .setInputCols(["token"]) \
  .setOutputCol("lemma") \
  .setDictionary("./lemmas001.txt")

normalizer = Normalizer() \
  .setInputCols(["token"]) \
  .setOutputCol("normalized")

Here are the errors:

# === from documentassembler ==============================================
  File "<ipython-input-7-e330f7904794>", line 1, in <module>
    documentAssembler = DocumentAssembler()  .setInputCol("text")  .setOutputCol("document")

  File "/home/quickt2/anaconda3/lib/python3.6/site-packages/pyspark/__init__.py", line 105, in wrapper
    return func(self, **kwargs)

  File "/home/quickt2/anaconda3/lib/python3.6/site-packages/sparknlp/base.py", line 175, in __init__
    super(DocumentAssembler, self).__init__(classname="com.johnsnowlabs.nlp.DocumentAssembler")

  File "/home/quickt2/anaconda3/lib/python3.6/site-packages/pyspark/__init__.py", line 105, in wrapper
    return func(self, **kwargs)

  File "/home/quickt2/anaconda3/lib/python3.6/site-packages/sparknlp/base.py", line 20, in __init__
    self._java_obj = self._new_java_obj(classname, self.uid)

  File "/home/quickt2/anaconda3/lib/python3.6/site-packages/pyspark/ml/wrapper.py", line 63, in _new_java_obj
    return java_obj(*java_args)

TypeError: 'JavaPackage' object is not callable

# === from lemmatizer ====================================================
Traceback (most recent call last):

  File "<ipython-input-11-793942a5767b>", line 1, in <module>
    lemmatizer = Lemmatizer()   .setInputCols(["token"])   .setOutputCol("lemma")   .setDictionary("./lemmas001.txt")

  File "/home/quickt2/anaconda3/lib/python3.6/site-packages/pyspark/__init__.py", line 105, in wrapper
    return func(self, **kwargs)

  File "/home/quickt2/anaconda3/lib/python3.6/site-packages/sparknlp/annotator.py", line 281, in __init__
    super(Lemmatizer, self).__init__(classname="com.johnsnowlabs.nlp.annotators.Lemmatizer")

  File "/home/quickt2/anaconda3/lib/python3.6/site-packages/pyspark/__init__.py", line 105, in wrapper
    return func(self, **kwargs)

  File "/home/quickt2/anaconda3/lib/python3.6/site-packages/sparknlp/annotator.py", line 95, in __init__
    self._java_obj = self._new_java_obj(classname, self.uid)

  File "/home/quickt2/anaconda3/lib/python3.6/site-packages/pyspark/ml/wrapper.py", line 63, in _new_java_obj
    return java_obj(*java_args)

TypeError: 'JavaPackage' object is not callable

# === from normalizer ====================================================
Traceback (most recent call last):

  File "<ipython-input-13-0cd941eb8a5d>", line 1, in <module>
    normalizer = Normalizer()   .setInputCols(["token"])   .setOutputCol("normalized")

  File "/home/quickt2/anaconda3/lib/python3.6/site-packages/pyspark/__init__.py", line 105, in wrapper
    return func(self, **kwargs)

  File "/home/quickt2/anaconda3/lib/python3.6/site-packages/sparknlp/annotator.py", line 198, in __init__
    super(Normalizer, self).__init__(classname="com.johnsnowlabs.nlp.annotators.Normalizer")

  File "/home/quickt2/anaconda3/lib/python3.6/site-packages/pyspark/__init__.py", line 105, in wrapper
    return func(self, **kwargs)

  File "/home/quickt2/anaconda3/lib/python3.6/site-packages/sparknlp/annotator.py", line 95, in __init__
    self._java_obj = self._new_java_obj(classname, self.uid)

  File "/home/quickt2/anaconda3/lib/python3.6/site-packages/pyspark/ml/wrapper.py", line 63, in _new_java_obj
    return java_obj(*java_args)

TypeError: 'JavaPackage' object is not callable

**Comment by saifjsl** [comment] 2018-07-04 11:09
Hi @bigheadming 

You **do** have this jar here and with this name right?

`.config("spark.driver.extraClassPath", **"lib/sparknlp.jar"**) `

**Comment by snape6666** [comment] 2018-07-25 15:09
I just installed spark-nlp for python and i get the same error... how do i fix this? i tried @saifjsl solution but didnt worked in my case...

any other suggestions? I dont understand why this isnt fixed by updating the install, its a well spread problem..^^

thx for help

```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-5-10341c54d325> in <module>()
      1 ### Define the dataframe
----> 2 document_assembler = DocumentAssembler()             .setInputCol("text")
      3 
      4 ### Transform input to appropriate schema
      5 #assembled = document_assembler.transform(data)

C:\ProgramData\Anaconda3\lib\site-packages\pyspark\__init__.py in wrapper(self, *args, **kwargs)
    103             raise TypeError("Method %s forces keyword arguments." % func.__name__)
    104         self._input_kwargs = kwargs
--> 105         return func(self, **kwargs)
    106     return wrapper
    107 

C:\ProgramData\Anaconda3\lib\site-packages\sparknlp\base.py in __init__(self)
    169     @keyword_only
    170     def __init__(self):
--> 171         super(DocumentAssembler, self).__init__(classname="com.johnsnowlabs.nlp.DocumentAssembler")
    172         self._setDefault(outputCol="document")
    173 

C:\ProgramData\Anaconda3\lib\site-packages\pyspark\__init__.py in wrapper(self, *args, **kwargs)
    103             raise TypeError("Method %s forces keyword arguments." % func.__name__)
    104         self._input_kwargs = kwargs
--> 105         return func(self, **kwargs)
    106     return wrapper
    107 

C:\ProgramData\Anaconda3\lib\site-packages\sparknlp\base.py in __init__(self, classname)
     18         self.setParams(**kwargs)
     19         self.__class__._java_class_name = classname
---> 20         self._java_obj = self._new_java_obj(classname, self.uid)
     21 
     22 

C:\ProgramData\Anaconda3\lib\site-packages\pyspark\ml\wrapper.py in _new_java_obj(java_class, *args)
     61             java_obj = getattr(java_obj, name)
     62         java_args = [_py2java(sc, arg) for arg in args]
---> 63         return java_obj(*java_args)
     64 
     65     @staticmethod

TypeError: 'JavaPackage' object is not callable
```

**Comment by saifjsl** [comment] 2018-07-25 19:31
@snape6666 it is not a problem in the library. The solution will depend on each Spark user, depending on their own environment.

Nowadays, Spark is widely spread used in different environments (Hadoop clusters with Yarn, Standalone with S3, Azure, Amazon EMR, etc..).

It is up to the user to understand his environment, in order to know how to make Spark executors be able to reach out JARS on a classpath. We would never be capable of covering all possible use cases since this would be impossible.

The issue here, is just a matter of Spark executors not finding the JAR in the appropriate classpath. It would happen with any Spark based library you can use.

**Closed** 2018-07-25 19:37 UTC

**Comment by snape6666** [comment] 2018-07-26 05:39
Thx for reply. I know that the system searches the JAR file. But which one?^^
I added the following without changes...

`os.environ['PYSPARK_SUBMIT_ARGS'] = '--jars C:/MYPATH/lib/spark-nlp-assembly-1.6.0.jar pyspark-shell'`

i exchanged MYPATH of course ;)

Or does the DocumentAssembler()   searches the spark...jar? Iam new in using spark so sorry for my stupid questions :">

**Comment by snape6666** [comment] 2018-07-26 05:57
ok can be closed. found this nice tutorial =)

https://changhsinlee.com/install-pyspark-windows-jupyter/

**Comment by yg37** [comment] 2018-11-26 18:40
Thanks @snape6666!

**Comment by ecmonsen** [comment] 2019-01-29 18:31
Thanks from me as well, @snape6666 !

**Comment by maziyarpanahi** [comment] 2019-01-30 10:16
Of course, you can download the provided JAR or Fat JAR and make it available to your Spark via many ways. However, if you are using `pip` or `conda` to install `spark-nlp` then when it comes to upgrading it you also have to manually come back and download the right JAR again!

The solution is to find `sparknlp.jar` path from your packages. For instance, `site-packages/sparknlp/lib/sparknlp.jar` is where mine is. If you have an environment, then you have to look inside your `env` directory. This way, every time you --upgrade, you won't be needing to download any external JAR since it comes with the Python package.

Example of `sparknlp.jar` with the environment called `spark`: `envs/spark/lib/python3.6/site-packages/sparknlp/lib/sparknlp.jar`
Python `environment` can be different places such as `Anaconda3` or in your home direcotry. Once you found it, then there is no need to keep downloading JAR and moving it to Spark directory. You just follow this Spark seesion code:


```Python
spark = SparkSession.builder \
    .appName("SentimentDetector")\
    .master("local[*]")\
    .config("spark.driver.memory","8G")\
    .config("spark.driver.maxResultSize", "2G")\
    .config("spark.driver.extraClassPath", "/Users/maziyar/anaconda3/envs/spark/lib/python3.6/site-packages/sparknlp/lib/sparknlp.jar")\
    .config("spark.executor.extraClassPath", "/Users/maziyar/anaconda3/envs/spark/lib/python3.6/site-packages/sparknlp/lib/sparknlp.jar")\
    .config("spark.jar", "/Users/maziyar/anaconda3/envs/spark/lib/python3.6/site-packages/sparknlp/lib/sparknlp.jar")\
    .config("spark.kryoserializer.buffer.max", "500m")\
    .getOrCreate()
```

**Comment by saifjsl** [comment] 2019-01-30 13:34
I think there's a typo on @maziyarpanahi answer. The config is `spark.jars` (plural)

**Comment by maziyarpanahi** [comment] 2019-01-30 14:02
Oh sorry! I'll edit it out since the other two are enough. I checked and there is no need for `spark.jars` to be set. Thanks @saifjsl 👍

**Comment by maziyarpanahi** [comment] 2019-02-12 16:19
Now you can just use Spark Packages instead of locating and pointing to sparknlp.jar:

```python
spark = SparkSession.builder \
    .appName("ner")\
    .master("local[4]")\
    .config("spark.driver.memory","4G")\
    .config("spark.driver.maxResultSize", "2G") \
    .config("spark.jars.packages", "JohnSnowLabs:spark-nlp:1.8.2")\
    .config("spark.kryoserializer.buffer.max", "500m")\
    .getOrCreate()
```

**Comment by eromoe** [comment] 2019-11-20 09:47
Only config `spark.jars` works for me , no need others 
```
SparkSession.builder.config("spark.jars", "hdfs://somepath/JohnSnowLabs:spark-nlp.jar")
```

**Comment by maziyarpanahi** [comment] 2020-03-19 18:36
Please join [Slack](https://join.slack.com/t/spark-nlp/shared_invite/enQtNjA4MTE2MDI1MDkxLWVjNWUzOGNlODg1Y2FkNGEzNDQ1NDJjMjc3Y2FkOGFmN2Q3ODIyZGVhMzU0NGM3NzRjNDkyZjZlZTQ0YzY1N2I) or create a [new issue](https://github.com/JohnSnowLabs/spark-nlp/issues/new/choose) if you are experiencing this problem.

**Comment by gordenstein72** [comment] 2020-07-07 20:51
Hi guys, Ive been getting this same "TypeError: 'JavaPackage' object is not callable " errortrying to call Document assembler. 

Python Version: 3.7.6
Environment: Anaconda3 (jupyter notebooks)
OS: win10

I've tried all of the install methods in the https://nlp.johnsnowlabs.com/docs/en/install 'cheat sheet' as well as manually adding the jar to the pyspark jars folder in my anaconda installation.

I've also tried running my SparkSession with `sparknlp.start()` and adding  `.config("spark.jars.packages", "com.johnsnowlabs.nlp:spark-nlp_2.11:2.5.3")` to the regular `SparkSession.builder` call.

thanks :)

**Comment by maziyarpanahi** [comment] 2020-07-08 12:47
Hi @gordenstein72 

Sometimes when you add another technology on top of your stack (Jupyter) it's hard to know the real error. So let's try to use a pure `pyspark` PyPI package

```
$ java -version
# should be Java 8 (Oracle or OpenJDK)

$ conda create -n sparknlp python=3.6 -y
$ conda activate sparknlp
$ pip install spark-nlp==2.5.3 pyspark==2.4.4

# do not close this terminal nor deactivate this env
# right here please write `python` so you can go to Python console
# now run the following commands to see what can be the real issue
```
```python
import sparknlp
# make sure the next command doesn't have any error or failed downloads
# this is where the JAR and the dependencies are being downloaded
# so if you are behind the firewall, or proxy or lose internet connectivity it won't load it
# and you see that error
spark = sparknlp.start()

spark.version
sparknlp.version()
```

That's all you need to use Spark NLP in PySpark. If you need more tests in the same Python console, you can follow these:

```python
from sparknlp.base import *
from sparknlp.annotator import *
from sparknlp.embeddings import *
from sparknlp.pretrained import PretrainedPipeline
import sparknlp

# Start Spark Session with Spark NLP
spark = sparknlp.start()

# Download a pre-trained pipeline 
pipeline = PretrainedPipeline(‘explain_document_dl’, lang=’en’)

# Your testing dataset
text = “””
The Mona Lisa is a 16th-century oil painting created by Leonardo. 
It’s held at the Louvre in Paris.
“””

# Annotate your testing dataset
result = pipeline.annotate(text)

# What’s in the pipeline
list(result.keys())

# Check the results
Result[‘entities’]
```

If you experience any issue, please provide detail steps of how you installed it, your environment, the full code and the full error so we can reproduce it.

**Comment by msteller-Ai** [comment] 2020-11-12 15:55
This issue appears again in Databricks on spark 3.0.1. Cloud you advise how to solve it there?

**Comment by maziyarpanahi** [comment] 2020-11-12 17:39
@msteller-Ai we don't support Spark 3.x, you can find the supported versions and Databricks runtimes:

https://github.com/JohnSnowLabs/spark-nlp#apache-spark-support

**Comment by mzeidhassan** [comment] 2021-02-24 05:28
Hi @maziyarpanahi ,
Sorry to reopen. Any idea when you plan to support "spark-3.0.1-bin-hadoop3.2"?
Thanks

**Comment by maziyarpanahi** [comment] 2021-02-24 06:13
No worries. There will be the first RC1 on 12 of March and hopefully the final release end of March.

**Comment by gabrielenizzoli** [comment] 2021-02-24 06:55
This is such an amazing news! Very much looking forward to test it.
________________________________

**Comment by mzeidhassan** [comment] 2021-02-24 21:51
Thanks a million for this great news!

**Comment by bjorn-johnson** [comment] 2021-03-19 16:11
> This issue appears again in Databricks on spark 3.0.1 and spark-nlp 2.6.0 (7.4 ML cluster). Cloud you advise how to solve it there?

Hey I see that sparknlp now supports spark 3.0. I'm getting the same error in Databricks. Any advise now?

**Comment by maziyarpanahi** [comment] 2021-03-19 17:02
We released a release candidate and announced it on the Slack. There is no final release available yet, when we release the final release it will be available in release notes, README, and the Maven repository as Spark NLP 3.0.0. (The old artifacts can’t just become compatible)

**Comment by maziyarpanahi** [comment] 2021-03-19 17:14
FYI: https://github.com/JohnSnowLabs/spark-nlp/releases/tag/3.0.0-rc8

**Comment by franckjay** [comment] 2021-05-18 18:25
I know this is closed, but if you are submitting this via a Qubole scheduled job, add in 
`--packages com.johnsnowlabs.nlp:spark-nlp-spark23_2.11:3.0.2` to the **Spark Submit Command Line Options** section

**Comment by maziyarpanahi** [comment] 2021-05-18 18:48
Thanks @franckjay 

Just to expand for the future users:


If you are using Spark NLP on spark/psypark 2.3.x or 2.4.x:

- com.johnsnowlabs.nlp:spark-nlp-spark23_2.11:3.0.3

- com.johnsnowlabs.nlp:spark-nlp-spark24_2.11:3.0.3


If you are using Spark NLP on spark/pyspark 3.0.x or 3.1.x:

- com.johnsnowlabs.nlp:spark-nlp-spark23_2.12:3.0.3

**Comment by latifaait** [comment] 2021-06-02 13:37
I got the same error
I use Java 11.0.10
and Spark NLP version:  3.0.3
Apache Spark version:  3.1.1
I am using windows, jupyter notebook
please help
 and this is the error, 
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-26-d2f186a3188f> in <module>
      5 
      6 spark = sparknlp.start()
----> 7 documentAssembler = DocumentAssembler()\
      8     .setInputCol("text")\
      9     .setOutputCol("document")

~\anaconda3\lib\site-packages\pyspark\__init__.py in wrapper(self, *args, **kwargs)
    112             raise TypeError("Method %s forces keyword arguments." % func.__name__)
    113         self._input_kwargs = kwargs
--> 114         return func(self, **kwargs)
    115     return wrapper
    116 

~\anaconda3\lib\site-packages\sparknlp\base.py in __init__(self)
    161     @keyword_only
    162     def __init__(self):
--> 163         super(DocumentAssembler, self).__init__(classname="com.johnsnowlabs.nlp.DocumentAssembler")
    164         self._setDefault(outputCol="document", cleanupMode='disabled')
    165 

~\anaconda3\lib\site-packages\pyspark\__init__.py in wrapper(self, *args, **kwargs)
    112             raise TypeError("Method %s forces keyword arguments." % func.__name__)
    113         self._input_kwargs = kwargs
--> 114         return func(self, **kwargs)
    115     return wrapper
    116 

~\anaconda3\lib\site-packages\sparknlp\internal.py in __init__(self, classname)
     85         self.setParams(**kwargs)
     86         self.__class__._java_class_name = classname
---> 87         self._java_obj = self._new_java_obj(classname, self.uid)
     88 
     89 

~\anaconda3\lib\site-packages\pyspark\ml\wrapper.py in _new_java_obj(java_class, *args)
     64             java_obj = getattr(java_obj, name)
     65         java_args = [_py2java(sc, arg) for arg in args]
---> 66         return java_obj(*java_args)
     67 
     68     @staticmethod

TypeError: 'JavaPackage' object is not callable

**Comment by maziyarpanahi** [comment] 2021-06-02 13:39
`I use Java 11.0.10`!

Requirements: https://github.com/JohnSnowLabs/spark-nlp#requirements

**Comment by latifaait** [comment] 2021-06-02 13:42
I have issue configurating Java 8 with Pyspark, only java 11.0.10 works for me. I have uninstalled java 11 and used java 8 and spark session not working.

**Comment by maziyarpanahi** [comment] 2021-06-02 14:07
I am sorry it's really hard to help with a minimum amount of information being provided and changed later. Please create a new issue, complete the template, provide all the required information including OS, versions, etc., provide steps to reproduce the error, and any snippet codes necessary.
