### ISSUE TITLE
S3 Cluster With no hadoop configuration instructions not working

### ISSUE THREAD

**Issue by acocu** [JohnSnowLabs/spark-nlp#758] opened 2020-01-28 15:53 UTC
## Description
In https://github.com/JohnSnowLabs/spark-nlp#s3-cluster the instructions contains the `ConfigLoader.setConfigPath("/somewhere/to/put/application.conf")
`. However, when using Spark NLP 2.3.6 it throws the following error: `error: value setConfigPath is not a member of object com.johnsnowlabs.util.ConfigLoader`. What is the proper solution?

## Steps to Reproduce

1.
2.
3.
4.

## Your Environment

* Spark NLP version: 2.3.6
* Apache NLP version: 2.4
* Setup and installation (Pypi, Conda, Maven, etc.):
* Operating System and version:
* Link to your project (if any):

**Comment by maziyarpanahi** [comment] 2020-01-28 15:54
Thanks for reporting this @acocu 
@rohit-nlp @saif-ellafi Do you guys have any idea? (Is our documentation outdated in README?)

**Comment by acocu** [comment] 2020-02-03 16:50
Hello,

I was wondering if there is any update on the issue.

On a  semi-related note, when trying to load a Spark NLP model from S3 locally it works, but when running it on the cluster it throws `Task not serializable ... Caused by: java.io.UTFDataFormatException: encoded string too long: 68804 bytes`. Do you suggest to open another ticket?

Thank you in advance for your time and help.

**Comment by maziyarpanahi** [comment] 2020-02-03 17:01
We are still investigating this, we are close to narrowing it down and find a way to fix this. I’ll keep the issue updated with our findings.

**Comment by acocu** [comment] 2020-02-03 17:06
Thank you for the prompt update!
I am actually using MESOS. Is there an existing link to check the status of that?

**Comment by maziyarpanahi** [comment] 2020-02-03 17:15
It may not be related to your issue, but it’s this one: https://github.com/JohnSnowLabs/spark-nlp/issues/745

In case it’s different since you are not on YARN, please create a new issue for that so we can follow up and reproduce it in case we need to.

Thank you

**Comment by maziyarpanahi** [comment] 2020-04-02 18:14
> Hello,
> 
> I was wondering if there is any update on the issue.
> 
> On a semi-related note, when trying to load a Spark NLP model from S3 locally it works, but when running it on the cluster it throws `Task not serializable ... Caused by: java.io.UTFDataFormatException: encoded string too long: 68804 bytes`. Do you suggest to open another ticket?
> 
> Thank you in advance for your time and help.

This has been resolved in 2.4.5 release: https://github.com/JohnSnowLabs/spark-nlp/releases/tag/2.4.5

**Closed by maziyarpanahi** 2020-04-02 18:14 UTC
Labels: question
