### ISSUE TITLE
Pretrained Explain Document DL for English no longer seems to work in Scala

### ISSUE THREAD

**Issue by Nickersoft** [JohnSnowLabs/spark-nlp#5854] opened 2021-07-21 19:58 UTC
## Description

I'm currently attempting to use the [Explain DL pipeline for English](https://github.com/JohnSnowLabs/spark-nlp/issues/new?assignees=maziyarpanahi&labels=&template=bug_report.md&title=) using `PretrainedPipeline("explain_document_dl", "en")`. However, when attempting to load the model I receive:

```
org.apache.spark.SparkException: Job aborted due to stage failure: Task 0 in stage 8.0 failed 1 times, most recent failure: Lost task 0.0 in stage 8.0 (TID 8) (10.0.0.32 executor driver): java.io.InvalidClassException: scala.collection.mutable.WrappedArray$ofRef; local class incompatible: stream classdesc serialVersionUID = 1028182004549731694, local class serialVersionUID = 3456489343829468865
        at java.base/java.io.ObjectStreamClass.initNonProxy(ObjectStreamClass.java:689)
        at java.base/java.io.ObjectInputStream.readNonProxyDesc(ObjectInputStream.java:2012)
        at java.base/java.io.ObjectInputStream.readClassDesc(ObjectInputStream.java:1862)
        at java.base/java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2169)
        at java.base/java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1679)
        at java.base/java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2464)
        at java.base/java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2358)
        at java.base/java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2196)
        at java.base/java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1679)
        at java.base/java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2464)
        at java.base/java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2358)
        at java.base/java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2196)
        at java.base/java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1679)
        at java.base/java.io.ObjectInputStream.readObject(ObjectInputStream.java:493)
        at java.base/java.io.ObjectInputStream.readObject(ObjectInputStream.java:451)
        at scala.collection.immutable.List$SerializationProxy.readObject(List.scala:527)
        at jdk.internal.reflect.GeneratedMethodAccessor29.invoke(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at java.base/java.io.ObjectStreamClass.invokeReadObject(ObjectStreamClass.java:1175)
        at java.base/java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2325)
        at java.base/java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2196)
        at java.base/java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1679)
        at java.base/java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2464)
        at java.base/java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2358)
        at java.base/java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2196)
        at java.base/java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1679)
        at java.base/java.io.ObjectInputStream.readArray(ObjectInputStream.java:2102)
        at java.base/java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1667)
        at java.base/java.io.ObjectInputStream.readObject(ObjectInputStream.java:493)
        at java.base/java.io.ObjectInputStream.readObject(ObjectInputStream.java:451)
        at org.apache.spark.util.Utils$.deserialize(Utils.scala:133)
        at org.apache.spark.SparkContext.$anonfun$objectFile$2(SparkContext.scala:1395)
        at scala.collection.Iterator$$anon$11.nextCur(Iterator.scala:486)
        at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:492)
        at scala.collection.Iterator$SliceIterator.hasNext(Iterator.scala:268)
        at scala.collection.Iterator.foreach(Iterator.scala:943)
        at scala.collection.Iterator.foreach$(Iterator.scala:943)
        at scala.collection.AbstractIterator.foreach(Iterator.scala:1431)
        at scala.collection.generic.Growable.$plus$plus$eq(Growable.scala:62)
        at scala.collection.generic.Growable.$plus$plus$eq$(Growable.scala:53)
        at scala.collection.mutable.ArrayBuffer.$plus$plus$eq(ArrayBuffer.scala:105)
        at scala.collection.mutable.ArrayBuffer.$plus$plus$eq(ArrayBuffer.scala:49)
        at scala.collection.TraversableOnce.to(TraversableOnce.scala:366)
        at scala.collection.TraversableOnce.to$(TraversableOnce.scala:364)
        at scala.collection.AbstractIterator.to(Iterator.scala:1431)
        at scala.collection.TraversableOnce.toBuffer(TraversableOnce.scala:358)
        at scala.collection.TraversableOnce.toBuffer$(TraversableOnce.scala:358)
        at scala.collection.AbstractIterator.toBuffer(Iterator.scala:1431)
        at scala.collection.TraversableOnce.toArray(TraversableOnce.scala:345)
        at scala.collection.TraversableOnce.toArray$(TraversableOnce.scala:339)
        at scala.collection.AbstractIterator.toArray(Iterator.scala:1431)
        at org.apache.spark.rdd.RDD.$anonfun$take$2(RDD.scala:1449)
        at org.apache.spark.SparkContext.$anonfun$runJob$5(SparkContext.scala:2236)
        at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:90)
        at org.apache.spark.scheduler.Task.run(Task.scala:131)
        at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$3(Executor.scala:497)
        at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1439)
        at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:500)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:834)
```

## Expected Behavior

I would expect the pipeline to work, seeing the Explain ML pipeline works, as well as the Explain pipelines I've tried for other languages. Explain DL says it supports SparkNLP 3.0.0+, which is what I'm using.

## Current Behavior

(see description)

## Possible Solution

It seems to be some kind of Scala/Spark version incompatibility – I think if the pipeline was retrained somehow it could possibly work. I was going to train my own version of the explain pipeline, but couldn't find any resources on training a lemmatization model (there doesn't seem to be a standalone pre-trained one on the models hub).

## Steps to Reproduce

I would imagine setting up a new project with the library versions below and attempting to load the pipeline would result in the same error, seeing the error is coming from inside Spark itself. I just haven't had the time to setup a reproduction repo.

## Context

I'm attempting to pretrain a pipeline that provides everything the DL pipeline does, however, I'm not sure how to obtain certain values (like lemmas) without the use of this pipeline.

## Your Environment

* Spark NLP version `sparknlp.version()`: 3.1.3
* Apache NLP version `spark.version`: 3.1.2
* Java version `java -version`: 8
* Scala version: 2.12.13
* Setup and installation (Pypi, Conda, Maven, etc.): Bazel w/ Scala Rules
* Operating System and version: macOS Big Sur 11.4
* Link to your project (if any): N/A

**Comment by maziyarpanahi** [comment] 2021-07-22 09:14
Hi,

Could you please share your full code, full error stack since I cannot see a cause in this one, and steps to reproduce this? 

I do have a macOS Big Sur and using Scala, however, I am not sure whether you are in spark-shell or an SBT project, etc. If you can elaborate on that with steps so I can follow would be great. (I've never encountered an issue and this is an SBT project with unit tests on macOS actually: https://github.com/maziyarpanahi/spark-nlp-starter)

**Comment by Nickersoft** [comment] 2021-07-22 18:31
@maziyarpanahi Thanks for the quick response! Unfortunately I can't share my original source code, as it's very complex and also private, but I was able to get a minimal reproduction setup in a new repo: https://github.com/Nickersoft/spark-nlp-failure. It uses Bazel, like my project. You just need to install Bazel or use Bazelisk and run `bazel run app`. The full stacktrace you receive is:

```
Exception in thread "main" java.lang.ExceptionInInitializerError
        at com.github.nickersoft.Main.main(Main.scala)
Caused by: org.apache.spark.SparkException: Job aborted due to stage failure: Task 0 in stage 8.0 failed 1 times, most recent failure: Lost task 0.0 in stage 8.0 (TID 8) (10.0.0.32 executor driver): java.io.InvalidClassException: scala.collection.mutable.WrappedArray$ofRef; local class incompatible: stream classdesc serialVersionUID = 1028182004549731694, local class serialVersionUID = 3456489343829468865
        at java.base/java.io.ObjectStreamClass.initNonProxy(ObjectStreamClass.java:689)
        at java.base/java.io.ObjectInputStream.readNonProxyDesc(ObjectInputStream.java:2012)
        at java.base/java.io.ObjectInputStream.readClassDesc(ObjectInputStream.java:1862)
        at java.base/java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2169)
        at java.base/java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1679)
        at java.base/java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2464)
        at java.base/java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2358)
        at java.base/java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2196)
        at java.base/java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1679)
        at java.base/java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2464)
        at java.base/java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2358)
        at java.base/java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2196)
        at java.base/java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1679)
        at java.base/java.io.ObjectInputStream.readObject(ObjectInputStream.java:493)
        at java.base/java.io.ObjectInputStream.readObject(ObjectInputStream.java:451)
        at scala.collection.immutable.List$SerializationProxy.readObject(List.scala:527)
        at jdk.internal.reflect.GeneratedMethodAccessor29.invoke(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at java.base/java.io.ObjectStreamClass.invokeReadObject(ObjectStreamClass.java:1175)
        at java.base/java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2325)
        at java.base/java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2196)
        at java.base/java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1679)
        at java.base/java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2464)
        at java.base/java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2358)
        at java.base/java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2196)
        at java.base/java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1679)
        at java.base/java.io.ObjectInputStream.readArray(ObjectInputStream.java:2102)
        at java.base/java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1667)
        at java.base/java.io.ObjectInputStream.readObject(ObjectInputStream.java:493)
        at java.base/java.io.ObjectInputStream.readObject(ObjectInputStream.java:451)
        at org.apache.spark.util.Utils$.deserialize(Utils.scala:133)
        at org.apache.spark.SparkContext.$anonfun$objectFile$2(SparkContext.scala:1395)
        at scala.collection.Iterator$$anon$11.nextCur(Iterator.scala:486)
        at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:492)
        at scala.collection.Iterator$SliceIterator.hasNext(Iterator.scala:268)
        at scala.collection.Iterator.foreach(Iterator.scala:943)
        at scala.collection.Iterator.foreach$(Iterator.scala:943)
        at scala.collection.AbstractIterator.foreach(Iterator.scala:1431)
        at scala.collection.generic.Growable.$plus$plus$eq(Growable.scala:62)
        at scala.collection.generic.Growable.$plus$plus$eq$(Growable.scala:53)
        at scala.collection.mutable.ArrayBuffer.$plus$plus$eq(ArrayBuffer.scala:105)
        at scala.collection.mutable.ArrayBuffer.$plus$plus$eq(ArrayBuffer.scala:49)
        at scala.collection.TraversableOnce.to(TraversableOnce.scala:348)
        at scala.collection.TraversableOnce.to$(TraversableOnce.scala:346)
        at scala.collection.AbstractIterator.to(Iterator.scala:1431)
        at scala.collection.TraversableOnce.toBuffer(TraversableOnce.scala:340)
        at scala.collection.TraversableOnce.toBuffer$(TraversableOnce.scala:340)
        at scala.collection.AbstractIterator.toBuffer(Iterator.scala:1431)
        at scala.collection.TraversableOnce.toArray(TraversableOnce.scala:327)
        at scala.collection.TraversableOnce.toArray$(TraversableOnce.scala:321)
        at scala.collection.AbstractIterator.toArray(Iterator.scala:1431)
        at org.apache.spark.rdd.RDD.$anonfun$take$2(RDD.scala:1449)
        at org.apache.spark.SparkContext.$anonfun$runJob$5(SparkContext.scala:2236)
        at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:90)
        at org.apache.spark.scheduler.Task.run(Task.scala:131)
        at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$3(Executor.scala:497)
        at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1439)
        at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:500)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:834)

Driver stacktrace:
        at org.apache.spark.scheduler.DAGScheduler.failJobAndIndependentStages(DAGScheduler.scala:2258)
        at org.apache.spark.scheduler.DAGScheduler.$anonfun$abortStage$2(DAGScheduler.scala:2207)
        at org.apache.spark.scheduler.DAGScheduler.$anonfun$abortStage$2$adapted(DAGScheduler.scala:2206)
        at scala.collection.mutable.ResizableArray.foreach(ResizableArray.scala:62)
        at scala.collection.mutable.ResizableArray.foreach$(ResizableArray.scala:55)
        at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:49)
        at org.apache.spark.scheduler.DAGScheduler.abortStage(DAGScheduler.scala:2206)
        at org.apache.spark.scheduler.DAGScheduler.$anonfun$handleTaskSetFailed$1(DAGScheduler.scala:1079)
        at org.apache.spark.scheduler.DAGScheduler.$anonfun$handleTaskSetFailed$1$adapted(DAGScheduler.scala:1079)
        at scala.Option.foreach(Option.scala:407)
        at org.apache.spark.scheduler.DAGScheduler.handleTaskSetFailed(DAGScheduler.scala:1079)
        at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.doOnReceive(DAGScheduler.scala:2445)
        at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:2387)
        at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:2376)
        at org.apache.spark.util.EventLoop$$anon$1.run(EventLoop.scala:49)
        at org.apache.spark.scheduler.DAGScheduler.runJob(DAGScheduler.scala:868)
        at org.apache.spark.SparkContext.runJob(SparkContext.scala:2196)
        at org.apache.spark.SparkContext.runJob(SparkContext.scala:2217)
        at org.apache.spark.SparkContext.runJob(SparkContext.scala:2236)
        at org.apache.spark.rdd.RDD.$anonfun$take$1(RDD.scala:1449)
        at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:151)
        at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:112)
        at org.apache.spark.rdd.RDD.withScope(RDD.scala:414)
        at org.apache.spark.rdd.RDD.take(RDD.scala:1422)
        at org.apache.spark.rdd.RDD.$anonfun$first$1(RDD.scala:1463)
        at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:151)
        at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:112)
        at org.apache.spark.rdd.RDD.withScope(RDD.scala:414)
        at org.apache.spark.rdd.RDD.first(RDD.scala:1463)
        at com.johnsnowlabs.nlp.serialization.StructFeature.deserializeObject(Feature.scala:120)
        at com.johnsnowlabs.nlp.serialization.Feature.deserialize(Feature.scala:47)
        at com.johnsnowlabs.nlp.FeaturesReader.$anonfun$load$1(ParamsAndFeaturesReadable.scala:15)
        at scala.collection.mutable.ResizableArray.foreach(ResizableArray.scala:62)
        at scala.collection.mutable.ResizableArray.foreach$(ResizableArray.scala:55)
        at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:49)
        at com.johnsnowlabs.nlp.FeaturesReader.load(ParamsAndFeaturesReadable.scala:14)
        at com.johnsnowlabs.nlp.FeaturesReader.load(ParamsAndFeaturesReadable.scala:8)
        at org.apache.spark.ml.Pipeline$SharedReadWrite$.$anonfun$load$5(Pipeline.scala:277)
        at org.apache.spark.ml.MLEvents.withLoadInstanceEvent(events.scala:160)
        at org.apache.spark.ml.MLEvents.withLoadInstanceEvent$(events.scala:155)
        at org.apache.spark.ml.util.Instrumentation.withLoadInstanceEvent(Instrumentation.scala:42)
        at org.apache.spark.ml.Pipeline$SharedReadWrite$.$anonfun$load$4(Pipeline.scala:277)
        at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:285)
        at scala.collection.IndexedSeqOptimized.foreach(IndexedSeqOptimized.scala:36)
        at scala.collection.IndexedSeqOptimized.foreach$(IndexedSeqOptimized.scala:33)
        at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:198)
        at scala.collection.TraversableLike.map(TraversableLike.scala:285)
        at scala.collection.TraversableLike.map$(TraversableLike.scala:278)
        at scala.collection.mutable.ArrayOps$ofRef.map(ArrayOps.scala:198)
        at org.apache.spark.ml.Pipeline$SharedReadWrite$.$anonfun$load$3(Pipeline.scala:274)
        at org.apache.spark.ml.util.Instrumentation$.$anonfun$instrumented$1(Instrumentation.scala:191)
        at scala.util.Try$.apply(Try.scala:213)
        at org.apache.spark.ml.util.Instrumentation$.instrumented(Instrumentation.scala:191)
        at org.apache.spark.ml.Pipeline$SharedReadWrite$.load(Pipeline.scala:268)
        at org.apache.spark.ml.PipelineModel$PipelineModelReader.$anonfun$load$7(Pipeline.scala:356)
        at org.apache.spark.ml.MLEvents.withLoadInstanceEvent(events.scala:160)
        at org.apache.spark.ml.MLEvents.withLoadInstanceEvent$(events.scala:155)
        at org.apache.spark.ml.util.Instrumentation.withLoadInstanceEvent(Instrumentation.scala:42)
        at org.apache.spark.ml.PipelineModel$PipelineModelReader.$anonfun$load$6(Pipeline.scala:355)
        at org.apache.spark.ml.util.Instrumentation$.$anonfun$instrumented$1(Instrumentation.scala:191)
        at scala.util.Try$.apply(Try.scala:213)
        at org.apache.spark.ml.util.Instrumentation$.instrumented(Instrumentation.scala:191)
        at org.apache.spark.ml.PipelineModel$PipelineModelReader.load(Pipeline.scala:355)
        at org.apache.spark.ml.PipelineModel$PipelineModelReader.load(Pipeline.scala:349)
        at com.johnsnowlabs.nlp.pretrained.ResourceDownloader$.downloadPipeline(ResourceDownloader.scala:397)
        at com.johnsnowlabs.nlp.pretrained.ResourceDownloader$.downloadPipeline(ResourceDownloader.scala:391)
        at com.johnsnowlabs.nlp.pretrained.PretrainedPipeline.<init>(PretrainedPipeline.scala:65)
        at com.github.nickersoft.Main$.<init>(Main.scala:6)
        at com.github.nickersoft.Main$.<clinit>(Main.scala)
        ... 1 more
Caused by: java.io.InvalidClassException: scala.collection.mutable.WrappedArray$ofRef; local class incompatible: stream classdesc serialVersionUID = 1028182004549731694, local class serialVersionUID = 3456489343829468865
        at java.base/java.io.ObjectStreamClass.initNonProxy(ObjectStreamClass.java:689)
        at java.base/java.io.ObjectInputStream.readNonProxyDesc(ObjectInputStream.java:2012)
        at java.base/java.io.ObjectInputStream.readClassDesc(ObjectInputStream.java:1862)
        at java.base/java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2169)
        at java.base/java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1679)
        at java.base/java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2464)
        at java.base/java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2358)
        at java.base/java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2196)
        at java.base/java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1679)
        at java.base/java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2464)
        at java.base/java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2358)
        at java.base/java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2196)
        at java.base/java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1679)
        at java.base/java.io.ObjectInputStream.readObject(ObjectInputStream.java:493)
        at java.base/java.io.ObjectInputStream.readObject(ObjectInputStream.java:451)
        at scala.collection.immutable.List$SerializationProxy.readObject(List.scala:527)
        at jdk.internal.reflect.GeneratedMethodAccessor29.invoke(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at java.base/java.io.ObjectStreamClass.invokeReadObject(ObjectStreamClass.java:1175)
        at java.base/java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2325)
        at java.base/java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2196)
        at java.base/java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1679)
        at java.base/java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2464)
        at java.base/java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2358)
        at java.base/java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2196)
        at java.base/java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1679)
        at java.base/java.io.ObjectInputStream.readArray(ObjectInputStream.java:2102)
        at java.base/java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1667)
        at java.base/java.io.ObjectInputStream.readObject(ObjectInputStream.java:493)
        at java.base/java.io.ObjectInputStream.readObject(ObjectInputStream.java:451)
        at org.apache.spark.util.Utils$.deserialize(Utils.scala:133)
        at org.apache.spark.SparkContext.$anonfun$objectFile$2(SparkContext.scala:1395)
        at scala.collection.Iterator$$anon$11.nextCur(Iterator.scala:486)
        at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:492)
        at scala.collection.Iterator$SliceIterator.hasNext(Iterator.scala:268)
        at scala.collection.Iterator.foreach(Iterator.scala:943)
        at scala.collection.Iterator.foreach$(Iterator.scala:943)
        at scala.collection.AbstractIterator.foreach(Iterator.scala:1431)
        at scala.collection.generic.Growable.$plus$plus$eq(Growable.scala:62)
        at scala.collection.generic.Growable.$plus$plus$eq$(Growable.scala:53)
        at scala.collection.mutable.ArrayBuffer.$plus$plus$eq(ArrayBuffer.scala:105)
        at scala.collection.mutable.ArrayBuffer.$plus$plus$eq(ArrayBuffer.scala:49)
        at scala.collection.TraversableOnce.to(TraversableOnce.scala:348)
        at scala.collection.TraversableOnce.to$(TraversableOnce.scala:346)
        at scala.collection.AbstractIterator.to(Iterator.scala:1431)
        at scala.collection.TraversableOnce.toBuffer(TraversableOnce.scala:340)
        at scala.collection.TraversableOnce.toBuffer$(TraversableOnce.scala:340)
        at scala.collection.AbstractIterator.toBuffer(Iterator.scala:1431)
        at scala.collection.TraversableOnce.toArray(TraversableOnce.scala:327)
        at scala.collection.TraversableOnce.toArray$(TraversableOnce.scala:321)
        at scala.collection.AbstractIterator.toArray(Iterator.scala:1431)
        at org.apache.spark.rdd.RDD.$anonfun$take$2(RDD.scala:1449)
        at org.apache.spark.SparkContext.$anonfun$runJob$5(SparkContext.scala:2236)
        at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:90)
        at org.apache.spark.scheduler.Task.run(Task.scala:131)
        at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$3(Executor.scala:497)
        at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1439)
        at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:500)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:834)
```

Hope this helps!

**Comment by maziyarpanahi** [comment] 2021-07-22 20:13
I understand. As a last clue, I see the following error:

serialVersionUID

this indicates you are trying something that was complied for Scala 2.11 in Scala 2.12 or vice versa. https://github.com/JohnSnowLabs/spark-nlp/discussions/2562

That’s being said, without a code it will take a lot of time an effort to debug this by keep guessing and asking. The link I shared should be enough for you to continue to debug and resolve your issue.

best of luck

**Comment by Nickersoft** [comment] 2021-07-22 21:08
@maziyarpanahi Could you elaborate on "without a code"? Do you mean error code? I linked re-production code in my previous comment which uses Scala 2.12, Spark 3.x, and still results in the same error. Your suggested solution in the linked discussion is to report that this is happening in case a model hasn't been updated to be compatible with the latest binaries, which is what I did:

![image](https://user-images.githubusercontent.com/2104129/126709576-ddb6e08a-a084-45fb-9246-3037bcf7d241.png)

The only other option I would have here is to train my own English lemmatizer, which doesn't seem possible seeing I can't find any resources on it. Please, I don't think there is enough here for me to resolve this issue on my own.

**Comment by Nickersoft** [comment] 2021-07-22 21:11
Also, both [the Explain DL pipeline](https://nlp.johnsnowlabs.com/2020/03/19/explain_document_dl.html) and the [Explain DL English pipeline](https://nlp.johnsnowlabs.com/2021/03/23/explain_document_dl_en.html), for SparkNLP 2.x and 3.x respectively, both use the same pipeline name in their example code: 

![image](https://user-images.githubusercontent.com/2104129/126710074-b8c5eea9-4168-41ee-b221-222a06a363d9.png)

I don't know if this could have something to do with it as well.

**Comment by maziyarpanahi** [comment] 2021-07-23 14:44
Hi @Nickersoft 

Sorry I missed the link to your code. There was something fixed for that pipeline in the latest release of `3.1.3`. Could you please bump the version to that and see what happens? 

PS: the error `serialVersionUID` is regarding having a model trained on Scala 2.11 and used in 2.12 or vice versa, but those models have been tested in all the Spark versions. We have the latest version for Scala 2.11 and 2.12 which is being downloaded automatically as you can see in my unit tests: https://github.com/maziyarpanahi/spark-nlp-starter/blob/279f866ecc748fa445f73490dc7065bf5e054de2/src/main/scala/Main.scala#L71 - even though we test this pipeline all the time everywhere, you can see the unit test passed on the macOS platform

**Comment by Nickersoft** [comment] 2021-07-23 17:57
@maziyarpanahi Thanks so much for re-opening this :) As mentioned in my original post though, I'm already using SparkNLP 3.1.3, and so is the reproduction repo I posted. I noticed that the `spark-nlp-starter` repo, however, uses Scala 2.12.10 while mine uses 2.12.13. There shouldn't be any binary incompatibilities across 3 patch versions, should there?

**Comment by Nickersoft** [comment] 2021-07-23 18:03
So I actually just did some experimenting – downgrading Spark to 3.0.3 from 3.1.2 in my linked repo works. Reading the release notes for [Spark 3.1.1](https://spark.apache.org/releases/spark-release-3-1-1.html) and [3.1.2](https://spark.apache.org/releases/spark-release-3-1-2.html) though, I can't seem to find anything that would imply backward incompatibility.

**Comment by maziyarpanahi** [comment] 2021-07-23 18:23
The official Scala versions for Apache Spark are:
- 2.11.12
- 2.12.10 (they tried with 2.12.13 but they had issues so they downgraded to 2.12.10 for some reason)

All of our scripts for Colab/Kaggle, default pyspark, and my own testings are actually on Apache Spark 3.1.2. And looking at Apache Spark 3.1.2 release notes nothing really changed in this release to cause any compatibility issue. 

Can't say for sure what is the issue with your setup when it comes to Apache Spark 3.1.2, but it should work without any issue on Scala 2.12.10. (I will test my SBT project with 3.1.2 just in case)

**Comment by Nickersoft** [comment] 2021-07-23 18:57
Yeah it's very strange... I just tested on my repro repo with Scala 2.11.12 and 2.12.10 with Spark 3.1.2 and got the error both times. Downgrading to Spark 3.0.3 is the only thing that works (Spark 3.1.1 also throws the error). 

I'm also curious if you could share where in the Spark docs it claims 2.11.12 and 2.12.10 are the officially supported Scala versions? All I could find is where it says Spark 3.0 is pre-built with Scala 2.12 and you need a 2.12.x version [to run it](https://spark.apache.org/docs/latest/#downloading):

![image](https://user-images.githubusercontent.com/2104129/126828695-bff9e021-86c5-4526-98e6-6cb88de051d9.png)

**Comment by maziyarpanahi** [comment] 2021-07-25 17:45
- Spark 3.0.x and 3.1.x are all on 2.12.10 : https://github.com/apache/spark/blob/de351e30a90dd988b133b3d00fa6218bfcaba8b8/pom.xml#L165
- Same goes for 2.3.x and 2.4.x which are on 2.11.12

I am closing this as it's not an issue, macOS locally and on GitHub actions work fine with Apache Spark 3.1.2 as I have updated the started project and we do extensive tests on all Apache Spark releases on all platforms (not that it was needed since nothing really changes in minor releases of Apache Spark): https://github.com/maziyarpanahi/spark-nlp-starter

I suspect something locally or mostly Bazel-related that might cause this.

**Closed by maziyarpanahi** 2021-07-25 17:45 UTC
Labels: Requires more input
