### ISSUE TITLE
Pretrained Pipeline fails on Standalone Cluster Mode

### ISSUE THREAD

**Issue by tooobsias** [JohnSnowLabs/spark-nlp#973] opened 2020-07-19 21:16 UTC
## Description

After successfully executing the [Spark_workshop-sentiment DL example](https://github.com/JohnSnowLabs/spark-nlp-workshop/blob/master/jupyter/training/english/classification/SentimentDL_train_multiclass_sentiment_classifier.ipynb) on my local MacBook I have transferred the Pipeline Model to another Ubuntu Machine and tried to execute a modified version of the code there. It works as expected in local mode but as soon as I start a master and slave on the same machine I encounter an unexpected error: `Caused by: org.tensorflow.TensorFlowException: not an sstable (bad magic number)`

Spark Command: `spark-submit --master spark://dear-bengal:7077  --driver-memory 5G --executor-memory 50G  --jars spark-nlp-assembly-2.5.2.jar spark_ml.py`

My Code is:

```
import sparknlp
from pyspark.ml import Pipeline
from sparknlp.annotator import *
from sparknlp.common import *
from sparknlp.base import *
from pyspark.sql import SparkSession


spark = SparkSession.builder \
.appName("ner") \
.master("spark://dear-bengal:7077") \
.config("spark.driver.memory","16G") \
.config("spark.driver.maxResultSize", "2G") \
.config("spark.jars", "/home/ubuntu/spark-nlp-assembly-2.5.2.jar") \
.config("spark.serializer", "org.apache.spark.serializer.KryoSerializer") \
.config("spark.kryoserializer.buffer.max", "1000m") \
.getOrCreate()



print("Spark NLP version: ", sparknlp.version())
print("Apache Spark version", spark.version)


from pyspark.sql.types import StringType

dfTest = spark.createDataFrame([
    "This movie is a delight for those of all ages. I have seen it several times and each time I am enchanted by the characters and magic. The cast is outstanding, the special ... ",
    "This film was to put it simply rubbish. The child actors couldn't act, as can be seen by Harry's supposed surprise on learning he's a wizard. I'm a wizard! "
], StringType()).toDF("text")


loadedPipeline = PipelineModel.load("./sentimentdl_pipeline")
result = loadedPipeline.transform(dfTest)

result.printSchema()
result.select("text", "class.result").show()
spark.stop()
```

## Actual

`20/07/19 21:08:56 WARN TaskSetManager: Lost task 0.0 in stage 10.0 (TID 12, 172.29.1.255, executor 0): org.apache.spark.SparkException: Failed to execute user defined function($a
nonfun$dfAnnotate$1: (array<array<struct<annotatorType:string,begin:int,end:int,result:string,metadata:map<string,string>,embeddings:array<float>>>>) => array<struct<annotatorTyp
e:string,begin:int,end:int,result:string,metadata:map<string,string>,embeddings:array<float>>>)
        at org.apache.spark.sql.catalyst.expressions.GeneratedClass$GeneratedIteratorForCodegenStage1.project_doConsume_0$(Unknown Source)
        at org.apache.spark.sql.catalyst.expressions.GeneratedClass$GeneratedIteratorForCodegenStage1.processNext(Unknown Source)
        at org.apache.spark.sql.execution.BufferedRowIterator.hasNext(BufferedRowIterator.java:43)
        at org.apache.spark.sql.execution.WholeStageCodegenExec$$anonfun$13$$anon$1.hasNext(WholeStageCodegenExec.scala:636)
        at org.apache.spark.sql.execution.SparkPlan$$anonfun$2.apply(SparkPlan.scala:255)
        at org.apache.spark.sql.execution.SparkPlan$$anonfun$2.apply(SparkPlan.scala:247)
        at org.apache.spark.rdd.RDD$$anonfun$mapPartitionsInternal$1$$anonfun$apply$24.apply(RDD.scala:858)
        at org.apache.spark.rdd.RDD$$anonfun$mapPartitionsInternal$1$$anonfun$apply$24.apply(RDD.scala:858)
        at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:52)
        at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:346)
        at org.apache.spark.rdd.RDD.iterator(RDD.scala:310)
        at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:52)
        at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:346)
        at org.apache.spark.rdd.RDD.iterator(RDD.scala:310)
        at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:90)
        at org.apache.spark.scheduler.Task.run(Task.scala:123)
        at org.apache.spark.executor.Executor$TaskRunner$$anonfun$10.apply(Executor.scala:408)
        at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1360)
        at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:414)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: org.tensorflow.TensorFlowException: not an sstable (bad magic number)
         [[{{node save/RestoreV2}}]]
        at org.tensorflow.Session.run(Native Method)
        at org.tensorflow.Session.access$100(Session.java:48)
        at org.tensorflow.Session$Runner.runHelper(Session.java:326)
        at org.tensorflow.Session$Runner.run(Session.java:276)
        at com.johnsnowlabs.ml.tensorflow.TensorflowWrapper.getSession(TensorflowWrapper.scala:64)
        at com.johnsnowlabs.ml.tensorflow.TensorflowSentiment.predict(TensorflowSentiment.scala:135)
        at com.johnsnowlabs.nlp.annotators.classifier.dl.SentimentDLModel.annotate(SentimentDLModel.scala:96)
        at com.johnsnowlabs.nlp.AnnotatorModel$$anonfun$dfAnnotate$1.apply(AnnotatorModel.scala:35)
        at com.johnsnowlabs.nlp.AnnotatorModel$$anonfun$dfAnnotate$1.apply(AnnotatorModel.scala:34)
        ... 22 more`

##  Environment

* Spark NLP version:  2.5.2
* Apache NLP version: 2.4.5
* Java version (java -version): 8
* Setup and installation (Pypi, Conda, Maven, etc.): Via Pip2
* Operating System and version: Ubuntu
* File System: Local, no Hadoop

**Comment by maziyarpanahi** [comment] 2020-07-20 01:22
Please make sure you have the following configs in your spark-submit and SparkSession:

spark.kryoserializer.buffer.max 1000M
spark.serializer org.apache.spark.serializer.KryoSerializer

**Comment by tooobsias** [comment] 2020-07-20 06:36
I have set the configs in spark-submit and in my Session and the WebUI shows that they are being set properly.
But still got the same results. Data is not stored on a HDFS, I just use the local file system.

Thats my code taken from the workshop example mentioned above:
```
from pyspark.ml import Pipeline
from sparknlp.annotator import *
from sparknlp.common import *
from sparknlp.base import *
from pyspark.sql import SparkSession
import sparknlp


spark = SparkSession.builder \
    .appName("ner") \
    .master("local[*]") \
    .config("spark.driver.memory","4G") \
    .config("spark.driver.maxResultSize", "2G") \
    .config("spark.jars", "spark-nlp-assembly-2.5.2.jar") \
    .config("spark.serializer", "org.apache.spark.serializer.KryoSerializer") \
    .config("spark.kryoserializer.buffer.max", "1000m") \
    .getOrCreate()



print("Spark NLP version: ", sparknlp.version())
print("Apache Spark version", spark.version)

trainDataset = spark.read \
      .option("header", True) \
      .csv("aclimdb_train.csv")

# actual content is inside description column
document = DocumentAssembler()\
    .setInputCol("text")\
    .setOutputCol("document")

use = UniversalSentenceEncoder.pretrained() \
 .setInputCols(["document"])\
 .setOutputCol("sentence_embeddings")

# the classes/labels/categories are in category column
sentimentdl = SentimentDLApproach()\
  .setInputCols(["sentence_embeddings"])\
  .setOutputCol("class")\
  .setLabelColumn("label")\
  .setMaxEpochs(5)\
  .setEnableOutputLogs(True)

pipeline = Pipeline(
    stages = [
        document,
        use,
        sentimentdl
    ])

pipelineModel = pipeline.fit(trainDataset)

pipelineModel.write().overwrite().save("sentimentdl_pipeline")
#loadedPipeline = PipelineModel.load("new_sentimentdl_pipeline")
spark.stop()
```

**Comment by tooobsias** [comment] 2020-07-20 20:48
To give you some more context: I have downloaded the analzye_sentiment_imdb Pipeline and put it on another Ubuntu Machine to Test it out. Same code as in the first block and also same results as mentioned above.

Environment: Ubuntu 18.04.4 LTS

**Comment by maziyarpanahi** [comment] 2020-07-24 09:24
`Caused by: org.tensorflow.TensorFlowException: not an sstable (bad magic number) ` This error is about the saved model being corrupted or not being saved correctly.

* Would something happens if you just write/save the SentimentDLModel and load it in a new pipeline as the notebook suggest instead of the pipeline? 

* Regarding `analzye_sentiment_imdb`, we don't have a pipeline/model with this name. Could you please provide the full code for this test? Did you use `analyze_sentimentdl_use_imdb` pipeline? or did you use `sentimentdl_use_imdb` model inside your pipeline?

**Comment by MatdeB-SL** [comment] 2020-07-30 09:27
Having the same issue with the 'analyze_sentimentdl_use_twitter` pipeline.

> Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/sparknlp/pretrained.py", line 107, in annotate
    return pipeline.annotate(target)
  File "/usr/local/lib/python3.7/site-packages/sparknlp/base.py", line 49, in annotate
    annotations = self._lightPipeline.annotateJava(target)
  File "/usr/lib/spark/python/lib/py4j-0.10.7-src.zip/py4j/java_gateway.py", line 1257, in __call__
    answer, self.gateway_client, self.target_id, self.name)
  File "/usr/lib/spark/python/lib/pyspark.zip/pyspark/sql/utils.py", line 63, in deco
    return f(*a, **kw)
  File "/usr/lib/spark/python/lib/py4j-0.10.7-src.zip/py4j/protocol.py", line 328, in get_return_value
    format(target_id, ".", name), value)
py4j.protocol.Py4JJavaError: An error occurred while calling o6754.annotateJava.
: org.tensorflow.TensorFlowException: not an sstable (bad magic number)
	 [[{{node save/RestoreV2}}]]
	at org.tensorflow.Session.run(Native Method)
	at org.tensorflow.Session.access$100(Session.java:48)
	at org.tensorflow.Session$Runner.runHelper(Session.java:326)
	at org.tensorflow.Session$Runner.run(Session.java:276)
	at com.johnsnowlabs.ml.tensorflow.TensorflowWrapper.getSession(TensorflowWrapper.scala:64)
	at com.johnsnowlabs.ml.tensorflow.TensorflowSentiment.predict(TensorflowSentiment.scala:135)
	at com.johnsnowlabs.nlp.annotators.classifier.dl.SentimentDLModel.annotate(SentimentDLModel.scala:96)
	at com.johnsnowlabs.nlp.LightPipeline$$anonfun$fullAnnotate$1.apply(LightPipeline.scala:32)
	at com.johnsnowlabs.nlp.LightPipeline$$anonfun$fullAnnotate$1.apply(LightPipeline.scala:20)
	at scala.collection.IndexedSeqOptimized$class.foldl(IndexedSeqOptimized.scala:57)
	at scala.collection.IndexedSeqOptimized$class.foldLeft(IndexedSeqOptimized.scala:66)
	at scala.collection.mutable.ArrayOps$ofRef.foldLeft(ArrayOps.scala:186)
	at com.johnsnowlabs.nlp.LightPipeline.fullAnnotate(LightPipeline.scala:20)
	at com.johnsnowlabs.nlp.LightPipeline.annotate(LightPipeline.scala:64)
	at com.johnsnowlabs.nlp.LightPipeline.annotateJava(LightPipeline.scala:80)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
	at py4j.Gateway.invoke(Gateway.java:282)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.GatewayConnection.run(GatewayConnection.java:238)
	at java.lang.Thread.run(Thread.java:748)


```python
import sparknlp
from sparknlp.pretrained import PretrainedPipeline

#create or get Spark Session

spark = sparknlp.start()

sparknlp.version()
spark.version

#download, load, and annotate a text by pre-trained pipeline

pipeline = PretrainedPipeline('analyze_sentimentdl_use_twitter', 'en')
result = pipeline.annotate('The Mona Lisa is a very bad 16th century oil painting created by Leonardo')
print(result)
```

Python 3, SparkNLP 5.4.1, Spark 2.4.5 running on an AWS EMR in a Jupyter notebook

**Comment by MatdeB-SL** [comment] 2020-07-30 09:57
Looks like an EMR compatability issue for me, have gone back to 5.27.0

**Comment by maziyarpanahi** [comment] 2020-07-30 09:59
Hi @MatdeB-SL 
Yes, due to our AWS SKD version, only two versions of EMR are supported in the current release:
https://github.com/JohnSnowLabs/spark-nlp#emr-support

**Comment by tombriles** [comment] 2020-10-09 17:39
I'm seeing this issue with 'analyze_sentimentdl_use_twitter' and 'analyze_sentimentdl_use_imdb' on Databricks Runtime Version 6.5 ML (includes Apache Spark 2.4.5, Scala 2.11), though only with transform(), not with annotate() (which works). I've tried redefining spark as sparknlp.start(), as well. To reproduce:

`import sparknlp
from sparknlp.pretrained import PretrainedPipeline
from pyspark.sql.types import StringType

print("Spark NLP version: " + sparknlp.version())
print("Spark version: " + spark.version)

pipeline = PretrainedPipeline('analyze_sentimentdl_use_imdb', lang='en')

df = spark.createDataFrame([
    "This film was to put it simply rubbish. The child actors couldn't act, as can be seen by Harry's supposed surprise on learning he's a wizard. I'm a wizard! "
], StringType()).toDF("text")

sent_df = pipeline.transform(df)

sent_df.collect()`

**Comment by maziyarpanahi** [comment] 2020-10-09 18:48
> I'm seeing this issue with 'analyze_sentimentdl_use_twitter' and 'analyze_sentimentdl_use_imdb' on Databricks Runtime Version 6.5 ML (includes Apache Spark 2.4.5, Scala 2.11), though only with transform(), not with annotate() (which works). I've tried redefining spark as sparknlp.start(), as well. 
> 
> 
> 
> Spark NLP version: 2.6.2
> 
> Spark version: 2.4.5
> 
> 
> 
> To reproduce:
> 
> 
> 
> ```import sparknlp
> 
> from sparknlp.pretrained import PretrainedPipeline
> 
> from pyspark.sql.types import StringType
> 
> 
> 
> print("Spark NLP version: " + sparknlp.version())
> 
> print("Spark version: " + spark.version)
> 
> 
> 
> pipeline = PretrainedPipeline('analyze_sentimentdl_use_imdb', lang='en')
> 
> 
> 
> df = spark.createDataFrame([
> 
>     "This film was to put it simply rubbish. The child actors couldn't act, as can be seen by Harry's supposed surprise on learning he's a wizard. I'm a wizard! "
> 
> ], StringType()).toDF("text")
> 
> 
> 
> sent_df = pipeline.transform(df)
> 
> 
> 
> sent_df.collect()

Please follow the instructions here as those configs are important: https://github.com/JohnSnowLabs/spark-nlp#databricks-cluster

I was also told that in the cluster settings it is better to enable autoscale for local file storage for persistance.

**Comment by tombriles** [comment] 2020-10-09 20:41
I already had the config options set up, but had not enabled local storage autoscaling. That seems to have fixed it!

Thanks very much for your help! Y'all might want to add that suggestion to the documentation (if it's there, I missed it).

**Comment by maziyarpanahi** [comment] 2020-12-04 20:47
This issue is addressed in this PR and will be in the next release.

**Comment by hakantekbas** [comment] 2020-12-26 08:06
I can reproduce same issue in dataproc.  When I read all messages in topic, some were able to run code. Is it possible to run  analyze_sentimentdl_use_imdb model by changing some parameter? If not, when are you planning to publish new version?

**Comment by maziyarpanahi** [comment] 2020-12-26 09:13
This issue will be resolved in the next release.

**Comment by hakantekbas** [comment] 2021-01-11 19:39
I tried version 2.7.1. 

sentimentdl_glove_imdb and sentimentdl_use_twitter is not working. But bad magic error disappeared.   New error  for **sentimentdl_use_twitter** is

> org.tensorflow.TensorFlowException: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for /tmp/cd0235c6e459_ner8022700133752587252/variables
> 	 [[{{node save/RestoreV2}}]]

New error  for **sentimentdl_glove_imdb** is
> java.lang.IllegalArgumentException: requirement failed: Found input column with storage metadata. But such ref does not match to the ref this annotator requires. Make sure you are loading the annotator with ref: glove_840B_300
  at scala.Predef$.require(Predef.scala:224)
  at com.johnsnowlabs.storage.HasStorageRef$class.validateStorageRef(HasStorageRef.scala:27)
  at com.johnsnowlabs.nlp.annotators.classifier.dl.SentimentDLModel.validateStorageRef(SentimentDLModel.scala:15)
  at com.johnsnowlabs.nlp.annotators.classifier.dl.SentimentDLModel.beforeAnnotate(SentimentDLModel.scala:91)
  at com.johnsnowlabs.nlp.AnnotatorModel._transform(AnnotatorModel.scala:49)
  at com.johnsnowlabs.nlp.AnnotatorModel.transform(AnnotatorModel.scala:79)
  at org.apache.spark.ml.PipelineModel$$anonfun$transform$1.apply(Pipeline.scala:306)
  at org.apache.spark.ml.PipelineModel$$anonfun$transform$1.apply(Pipeline.scala:306)
  at scala.collection.IndexedSeqOptimized$class.foldl(IndexedSeqOptimized.scala:57)
  at scala.collection.IndexedSeqOptimized$class.foldLeft(IndexedSeqOptimized.scala:66)
  at scala.collection.mutable.ArrayOps$ofRef.foldLeft(ArrayOps.scala:186)
  at org.apache.spark.ml.PipelineModel.transform(Pipeline.scala:306)
  ... 65 elided


I'm running my code in dataproc 1.4.   classifierdl_use_sarcasm, classifierdl_use_spam, classifierdl_use_cyberbullying is running.

Thanks.

**Comment by maziyarpanahi** [comment] 2021-01-11 20:45
Thanks @hakantekbas 

As explained in the release notes, the 2.7.1 release requires new models to be trained. That specific model hasn't been trained yet. I am guessing since they are larger they are still in the process. They will be retrained this week and joined the others without any issue. 
You can follow the new classification models for 2.7.1 here: https://nlp.johnsnowlabs.com/models

**Comment by ankurphutela** [comment] 2021-02-22 07:37
Thanks @maziyarpanahi Can you please share status. Is model - 'analyze_sentimentdl_use_imdb_en' retrained?

**Comment by maziyarpanahi** [comment] 2021-02-22 07:44
Yes, every classifier models were trained again with 2.7.1 release as of now.

**Closed by maziyarpanahi** 2021-02-22 07:45 UTC
Labels: bug, fixed-next-release
