### ISSUE TITLE
Cannot find entity match in NerCrfApproach

### ISSUE THREAD

**Issue by Crisliu** [JohnSnowLabs/spark-nlp#101] opened 2018-02-07 16:04 UTC
## Description

When using NerCrfApproach, it returns error message below. I use a simple text data to test, which includes 'Walmart is in Germany‘, but it cannot find any matching on 'Germany', even that 'Germany' is contained in the test_ner_dataset.txt

## Expected Behavior

It should find some match from the simple test data.

## Current Behavior

Error message: java.util.NoSuchElementException: None.get

## Steps to Reproduce

1. ## Create sample data:
val data = Seq(
  (1, "Apple is located in California . It is a great company.</xml>"),
  (2, "Google is located in California . It is a great company.</xml>"),
  (3, "The BBC is located in London . It is a great company.</xml>"),
  (5, "The Walmart is located in Germany  . It is a great company.</xml>")
).toDF("id", "text")

2. ## Create pipeline for pre-transformation before fitting into NER

import com.johnsnowlabs.nlp.annotators.sbd.pragmatic.SentenceDetector
import com.johnsnowlabs.nlp.annotators.sda.vivekn.ViveknSentimentApproach
val documentAssembler = new DocumentAssembler()
    .setInputCol("text")
    .setOutputCol("document")

val sentenceDetector = new SentenceDetector()
    .setInputCols("document")
    .setOutputCol("sentence")

val regexTokenizer = new com.johnsnowlabs.nlp.annotators.Tokenizer()  // it is imported twice in the same scope by import com.johnsnowlabs.nlp.annotators._ and import org.apache.spark.ml.feature.Tokenizer
      .setInputCols(Array("sentence"))
      .setOutputCol("token")  
val positivePhrases = "/dbfs/FileStore/tables/positivePhrases.txt" 
val negativePhrases = "/dbfs/FileStore/tables/negativePhrases.txt"

val ViveknSentiment = new ViveknSentimentApproach()
        .setInputCols(Array("token", "sentence"))
        .setOutputCol("vivekn")
        .setPositiveSourcePath(positivePhrases)  
        .setNegativeSourcePath(negativePhrases)

val posTagger = new PerceptronApproach()  // https://github.com/JohnSnowLabs/spark-nlp/issues/41
    .setInputCols(Array("sentence", "token"))
    .setOutputCol("pos")

val finisher = new Finisher() 
      .setInputCols("token")
      .setCleanAnnotations(false) 

val pipeline2 = new Pipeline()
      .setStages(Array(
          documentAssembler, 
          sentenceDetector, 
          regexTokenizer ,  // works except for pattern
          ViveknSentiment, 
          posTagger,
          finisher 
      ))

var result2 = pipeline2
    .fit(data.select("id","text"))
    .transform(data.select("id","text"))
3. Fit in NER, which produces error:

val res3 = new NerCrfApproach()
  .setInputCols("sentence", "token", "pos")
  .setDatasetPath("src/test/resources/ner-corpus/test_ner_dataset.txt")
  .setOutputCol("ner")
  .fit(result2)

 Error meesage:  java.util.NoSuchElementException: None.get

## Your Environment

* Version used:
* Browser Name and version:
* Operating System and version (desktop or mobile):
* Link to your project:

**Comment by aleksei-ai** [comment] 2018-02-13 14:17
@Crisliu May I ask you to attach full exception (with stack)?

**Comment by saifjsl** [comment] 2018-02-23 20:30
I think I could reproduce it, this happens directly in our examples jupyter notebooks. I'll take a look

**Comment by saifjsl** [comment] 2018-02-23 21:30
@aleksei-ai this seems to happen because function embeddings() is being called even when sourceEmbeddingsPath has not been set. I'll need your help here, since this is being used.

This should be fixed by 1.4.1.

Thanks @Crisliu for reporting it.

**Comment by aleksei-ai** [comment] 2018-02-24 11:49
The bug is fixed. Thank you @saifjsl !

**Closed** 2018-03-06 16:33 UTC
Labels: bug
