### ISSUE TITLE
DocumentAssembler().setIdCol() throws error

### ISSUE THREAD

**Issue by clayms** [JohnSnowLabs/spark-nlp#54] opened 2017-12-09 21:29 UTC
This code:

```
documentAssembler = DocumentAssembler() \
  .setInputCol("input") \
  .setOutputCol("output") \
  .setIdCol("id")
```

throws this error:

```
AttributeError: 'DocumentAssembler' object has no attribute 'idCol'
AttributeErrorTraceback (most recent call last)
in engine
----> 1 documentAssembler = DocumentAssembler()   .setInputCol("input")   .setOutputCol("output")   .setIdCol("id")

/home/cdsw/sparknlp/base.pyc in setIdCol(self, value)
     31 
     32     def setIdCol(self, value):
---> 33         return self._set(idCol=value)
     34 
     35     def setMetadataCol(self, value):

/opt/cloudera/parcels/SPARK2/lib/spark2/python/pyspark/ml/param/__init__.py in _set(self, **kwargs)
    414         """
    415         for param, value in kwargs.items():
--> 416             p = getattr(self, param)
    417             if value is not None:
    418                 try:

AttributeError: 'DocumentAssembler' object has no attribute 'idCol'
```

Changing line 33 of sparknlp base.py from:  
  `return self._set(idCol=value)`  
to:  
  `return self._set(idColName=value)`    
fixed the problem for me.

**Comment by aleksei-ai** [comment] 2017-12-14 08:58
As I understand it's duplicate of issue https://github.com/JohnSnowLabs/spark-nlp/issues/56.
If I'm wrong fill free to reopen it.

**Closed by aleksei-ai** 2017-12-14 08:58 UTC
Labels: duplicate
