### ISSUE TITLE
Not able to download pretrained models

### ISSUE THREAD

**Issue by subarnab219** [JohnSnowLabs/spark-nlp#870] opened 2020-04-24 16:05 UTC
I just followed the documentation to run sparknlp

## Description
As mentioned in the getstarted document, imported the libraries, created a spark session and download the pretrained model

## Expected Behavior
Hopefully it should have downloaded explain_document_dl

## Current Behavior
Getting Py4JError  error

## Steps to Reproduce
from sparknlp.base import *
from sparknlp.annotator import *
from sparknlp.pretrained import PretrainedPipeline
import sparknlp
spark = sparknlp.start()
pipeline = PretrainedPipeline('explain_document_dl', lang='en')

Error:
---------------------------------------------------------------------------
Py4JError                                 Traceback (most recent call last)
<ipython-input-3-e6bf2fc16523> in <module>
      1 
      2 # Download a pre-trained pipeline
----> 3 pipeline = PretrainedPipeline('explain_document_dl', lang='en')

~/anaconda3/lib/python3.7/site-packages/sparknlp/pretrained.py in __init__(self, name, lang, remote_loc, parse_embeddings, disk_location)
     89     def __init__(self, name, lang='en', remote_loc=None, parse_embeddings=False, disk_location=None):
     90         if not disk_location:
---> 91             self.model = ResourceDownloader().downloadPipeline(name, lang, remote_loc)
     92         else:
     93             self.model = PipelineModel.load(disk_location)

~/anaconda3/lib/python3.7/site-packages/sparknlp/pretrained.py in downloadPipeline(name, language, remote_loc)
     58             t1.start()
     59             try:
---> 60                 j_obj = _internal._DownloadPipeline(name, language, remote_loc).apply()
     61                 jmodel = PipelineModel._from_java(j_obj)
     62             finally:

~/anaconda3/lib/python3.7/site-packages/sparknlp/internal.py in __init__(self, name, language, remote_loc)
    179 class _DownloadPipeline(ExtendedJavaWrapper):
    180     def __init__(self, name, language, remote_loc):
--> 181         super(_DownloadPipeline, self).__init__("com.johnsnowlabs.nlp.pretrained.PythonResourceDownloader.downloadPipeline", name, language, remote_loc)
    182 
    183 

~/anaconda3/lib/python3.7/site-packages/sparknlp/internal.py in __init__(self, java_obj, *args)
    127         super(ExtendedJavaWrapper, self).__init__(java_obj)
    128         self.sc = SparkContext._active_spark_context
--> 129         self._java_obj = self.new_java_obj(java_obj, *args)
    130         self.java_obj = self._java_obj
    131 

~/anaconda3/lib/python3.7/site-packages/sparknlp/internal.py in new_java_obj(self, java_class, *args)
    137 
    138     def new_java_obj(self, java_class, *args):
--> 139         return self._new_java_obj(java_class, *args)
    140 
    141     def new_java_array(self, pylist, java_class):

~/anaconda3/lib/python3.7/site-packages/pyspark/ml/wrapper.py in _new_java_obj(java_class, *args)
     65             java_obj = getattr(java_obj, name)
     66         java_args = [_py2java(sc, arg) for arg in args]
---> 67         return java_obj(*java_args)
     68 
     69     @staticmethod

~/anaconda3/lib/python3.7/site-packages/py4j/java_gateway.py in __call__(self, *args)
   1255         answer = self.gateway_client.send_command(command)
   1256         return_value = get_return_value(
-> 1257             answer, self.gateway_client, self.target_id, self.name)
   1258 
   1259         for temp_arg in temp_args:

~/anaconda3/lib/python3.7/site-packages/pyspark/sql/utils.py in deco(*a, **kw)
     61     def deco(*a, **kw):
     62         try:
---> 63             return f(*a, **kw)
     64         except py4j.protocol.Py4JJavaError as e:
     65             s = e.java_exception.toString()

~/anaconda3/lib/python3.7/site-packages/py4j/protocol.py in get_return_value(answer, gateway_client, target_id, name)
    334             raise Py4JError(
    335                 "An error occurred while calling {0}{1}{2}".
--> 336                 format(target_id, ".", name))
    337     else:
    338         type = answer[1]

Py4JError: An error occurred while calling z:com.johnsnowlabs.nlp.pretrained.PythonResourceDownloader.downloadPipeline

**Comment by maziyarpanahi** [comment] 2020-04-24 16:28
Please complete the template, we need that information. 

For versions, please copy the following commands:
```python
import sparknlp
sparknlp.version()
spark.version()
```

**Comment by knjpollard** [comment] 2021-10-17 05:44
Same error here as well. 
Py4JError: An error occurred while calling z:com.johnsnowlabs.nlp.pretrained.PythonResourceDownloader.downloadModel

Works on Databricks and Colab. Great, but breaks on my (Hadoop + Spark/Yarn) situation. It creates a giant log when it breaks. Too big to paste here. It seems fairly common so please fix or let me know how to fix.

**Comment by maziyarpanahi** [comment] 2021-10-17 07:59
Hi @knjpollard 
This issue can happen for a variety of issues that have nothing to do with the source code and more with the user's environment. (if you browse the similar issues you can see it has always been about how Spark NLP is setup, where it is being used, and whether or not the Apache Spark configurations are correctly set).

In that spirit, this cannot be resolved by a 1 line error since it's pretty generic and can be the same error if you don't have Internet. Please create a new issue, try to complete the template as much as possible for us to reproduce, and guide you on what could be wrong in your Hadoop/Spark/YARN setup. (sample code, full error/gist, all the info regarding OS, etc. are required)

**Closed by maziyarpanahi** 2021-10-17 07:59 UTC
Labels: Requires more input
